name: "Collect release notes action"
description: "Collects release notes from current release"
inputs:
  GITHUB_TOKEN:
    description: "Github token"
    required: true
    default: "1"
runs:
  using: "node16"
  main: "index.js"
