on: workflow_dispatch
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to collect release notes
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Collect release notes action step
        run: |
          cd ./
          npm install
          node index.js ${{ secrets.PERSONAL_ACCESS_TOKEN }}
